### ISSUE TITLE
download dataset ?

### ISSUE THREAD

**Issue by Nal44** [UFISH-Team/U-FISH#4]
HI,

I tried to download the spot dataset using the instruction but :

git clone https://huggingface.co/datasets/GangCaoLab/FISH_spots
Cloning into 'FISH_spots'...
remote: Repository not found
fatal: repository 'https://huggingface.co/datasets/GangCaoLab/FISH_spots/' not found

Can you please send the instructions to download the dataset ? that will be very useful.

Thanks a lot,
antho

**Comment by Nanguage** [comment]
Because our paper has not been published yet, the dataset has not been made public. After it is made public, we will provide updates here.

**Comment by Nal44** [comment]
Ok Thanks, I am looking for a spot dataset, I will keep looking, thanks for your work :)

**Comment by Nanguage** [comment]
Hi antho,

We have made the dataset public here: https://huggingface.co/datasets/GangCaoLab/FISH_spots
And you can explore it using our web app at here: https://ufish-team.github.io/#/dataset

Best,
Weize

**Comment by Nal44** [comment]
Hi Weize,

Thanks a lot :) 
I am working on the refinement as well, once working I can create a dataset as well with the curated spots :)

Antho
